[build]
publish = ".next"
command = "yarn build"

[build.environment]
NODE_VERSION = "18"

[functions]
included_files = ["content/**"]

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.